config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  resources :addresses, :except => [:new, :create]
  get 'addresses/new/:id' => 'addresses#new', as: :new_address
  post 'addresses/:id' => 'addresses#create'

  get '*not_found' => 'errors#not_found', as: :not_found

  root "contacts#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_one :address
end

app/controllers/addresses_controller.rb
#Require the script of common functions
require "common_functions"

class AddressesController < ApplicationController
  #Set a before action to reduce code redundency
  before_action :find_all, only: [:edit, :update, :destroy]
  before_action :find_contact, only: [:new, :create]

  #Address Index page
  def index
    #The User is redirected to the contacts listing
    #A contact must be selected to interact with Address info
    redirect_to "/contacts"
  end

  #New Address route
  def new
    #Create an empty Address for the form to use
    @address = Address.new
  end

  #Create Address page (POST)
  def create
    #Create an Address using the form parameters permitted
    @address = Address.new(address_params)
    #Set the newly created address to reference the correct Contact
    @address.contact_id = params[:id]

    #Check if the Address insert was successful
    if @address.save
      #Redirect to the referenced contact to see changes
      redirect_to @contact
    end
  end

  #Update address details (PUT/PATCH)
  def update
    #Try and update the record using form posts
    if @address.update(address_params)
      #Show referenced contact with updated address info upon success
      redirect_to @contact
    else
      #Go back to edit page if failure occurred
      render 'edit'
    end
  end

  #Delete Address record (DELETE)
  def destroy
    #Delete the address and redirect to referenced contact
    @address.destroy
    redirect_to @contact
  end

  def edit
  end

  #Define private functions
  private

  #Private function for multiple controllers
  def find_all
    #Find the contact and address based on URL id
    @contact = Contact.find(params[:id])
    @address = Address.find_by(contact_id: params[:id])
  end

  #Control form paramters
  def address_params
    #List the permitted fields being added to a Address record
    params.require(:address).permit(
      :street_name,
      :city,
      :province,
      :postal_code
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActionController::RoutingError, with: :render_404

  def render_404
    redirect_to 'errors/not_found'
  end
end

app/controllers/common_functions.rb
#Find a Contact using a URL id parameter
def find_contact

  #Check if the URL parameter is valid
  if params.has_key?(:id) && params[:id].to_i > 0
    #Find the contact based on Contact id passed
    @contact = Contact.find(params[:id])
  else
    #Redirect home on failure
    redirect_to root_path
  end
end

app/controllers/contacts_controller.rb
#Require the script of common functions
require "common_functions"

class ContactsController < ApplicationController
  #Set a before action to reduce code redundency
  before_action :find_contact, only: [:show, :edit, :update, :destroy]

  #Index page
  #Retrieve all contacts in descending order
  def index
    @contacts = Contact.all.order("created_at DESC")
  end

  #New Contact route
  #Create an empty Contact for the form to use
  def new
    @contact = Contact.new
  end

  #New Contact page (POST)
  def create
    #Create a new contact based on the contact form fields
    @contact = Contact.new(contact_params)

    #Try to save the new Contact
    if @contact.save
      #Go to the newly created contact if successful
      redirect_to @contact
    else
      #Redirect to the create contact form if not successful
      render 'new'
    end
  end

  #Update the Contact submitted (PUT/PATCH)
  def update
    #Check if updating Contact with form paramters is successful
    if @contact.update(contact_params)
      #Go to the Contact updated
      redirect_to @contact
    else
      #Go back to edit screen if something went wrong
      render 'edit'
    end
  end

  #Delete the Contact record (DELETE)
  def destroy
    #Delete from database and redited back home
    @contact.destroy
    redirect_to root_path
  end

  #Show Contact selected
  def show
    #Find the address tied to the current contact
    @address = Address.find_by(contact_id: params[:id])

    #Return empty object if no Address was found
    if !@address
      @address = Address.new
    end
  end

  def edit
  end

  #Define private functions
  private

  #Control form paramters
  def contact_params
    #List the permitted fields being added to a Contact record
    params.require(:contact).permit(
      :fname,
      :lname,
      :phone
    )
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render 'errors/not_found'
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/views/addresses/_address_form.html.erb
<%= form_for @address, :url => {:action => 'create', :id => @contact.id} do |form_elem| %>

  <%= form_elem.text_field :street_name,
    placeholder: "Street Name...",
    class: "form-control",
    required: "required" %><br/>

  <%= form_elem.text_field :city,
    placeholder: "City...",
    class: "form-control",
    required: "required" %><br/>

  <%= form_elem.text_field :province,
    placeholder: "Province...",
    class: "form-control",
    required: "required" %><br/>

  <%= form_elem.text_field :postal_code,
    placeholder: "Postal Code...",
    class: "form-control",
    required: "required" %><br/>

  <%= form_elem.submit "Submit", :class => "btn btn-success" %>

<% end %>

app/views/addresses/edit.html.erb
<h2>Edit Address Information</h2>
<hr/>

<div class="row">
  <div class="col-md-6">
    <h4><%= @contact.fname + " " + @contact.lname %></h4>
    <h5><%= @contact.phone%></h5>
  </div>

  <div class="col-md-6">
    <%= render "address_form" %>
  </div>
</div>

app/views/addresses/new.html.erb
<h2> Add Address to Contact</h2>
<hr/>

<div class="row">
  <div class="col-md-4">
    <h4><%= @contact.fname + " " + @contact.lname %></h4>
    <h5><%= @contact.phone%></h5>
  </div>

  <div class="col-md-8">
    <p>Please fill out the form below to add an address.</p>
    <br/>

    <%= render "address_form" %>
  </div>
</div>

app/views/contacts/_contact_form.html.erb
<%= form_for @contact do |form_elem| %>

  <%= form_elem.text_field :fname,
    placeholder: "First Name...",
    class: "form-control",
    required: "required" %><br/>

  <%= form_elem.text_field :lname,
    placeholder: "Last Name...",
    class: "form-control",
    required: "required" %><br/>

  <%= form_elem.text_field :phone,
    placeholder: "Phone Number...",
    class: "form-control",
    required: "required" %><br/>

  <%= form_elem.submit "Submit", :class => "btn btn-success" %>
<% end %>

app/views/contacts/edit.html.erb
<h2> Edit Contact </h2>
<hr/>

<p>
  Please edit the contact fields below and submit to propigate changes.
</p>

<%= render "contact_form" %>

app/views/contacts/index.html.erb
<h2> All Contacts </h2>
<hr/>

<table class="table table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Phone #</th>
      </tr>
    </thead>
    <tbody>
      <%
        if @contacts.length > 0
          #Loop through all existing contacts
          @contacts.each do |contact|
      %>
        <tr>
          <td>
            <%=
              #Set a link to the name of each contact
              link_to contact.fname, contact
            %>
          </td>
          <td><%= contact.lname %></td>
          <td><%= contact.phone %></td>
        </tr>
      <% end
        else %>
        <tr>
          <td colspan="3" style="text-align: center;">There where no contacts found!</td>
        </tr>
      <%end %>
    </tbody>
</table>
<br/>

<%= link_to "Create Contact", new_contact_path, class: "btn btn-primary", role: "button"%>

app/views/contacts/new.html.erb
<h2> Create a new Contact </h2>
<hr/>

<p>
  Please fill out the form below to create a new contact.
</p>

<%= render "contact_form" %>

app/views/contacts/show.html.erb
<h2> Contact Information</h2>
<hr/>

<div class="row">
  <div class="col-md-6">
    <h4><%= @contact.fname + " " + @contact.lname %></h4>
    <h5><%= @contact.phone%></h5>
  </div>

  <div class="col-md-6">
    <% if @address.id %>
      <h4><%= @address.street_name %></h4>
      <h5><%= @address.city %></h5>
      <h5><%= @address.province %></h5>
      <h5><%= @address.postal_code %></h5>
      <br/>
      <%= link_to "Edit Address", edit_address_path, class: "btn btn-default" %>

      <%= link_to "Delete Address",
        address_path,
        method: :delete,
        data: {
          confirm: "Are you sure? This address will be deleted!"
        },
        class: "btn btn-warning"
      %>
      
    <% else %>
      <%= link_to "Add Address", new_address_path, class: "btn btn-success" %>
    <% end %>

  </div>
</div>

<br/>
<div class="row">
  <%= link_to "Edit Contact", edit_contact_path, class: "btn btn-primary" %>

  <%= link_to "Delete Contact",
    contact_path,
    method: :delete,
    data: {
      confirm: "Are you sure? This contact will be deleted!"
    },
    class: "btn btn-danger"
  %>
</div>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Address Book", root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to "Create Contact", new_contact_path %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Ruby Address Book</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag 'bootstrap.min' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>

    <div id="mainContent" class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>

  </body>

  <!-- jQuery Version 1.11.1 -->
  <%= javascript_include_tag 'jquery' %>

  <!-- Bootstrap Core JavaScript -->
  <%= javascript_include_tag 'bootstrap.min' %>
</html>